version: '3'

services:
  pgjogos:
    image: postgres:alpine
    ports:
      - '5433:5433'
    container_name: 'pgjogos'
    restart: always
    volumes:
      - pg-jogo:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  pg-jogo:
